INSERT INTO drinks (name, type, liquor_id) VALUES ('Titos & Soda', 'Cocktail', 1);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Vodka Tonic', 'Cocktail', 1);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Stormin Sailor', 'Cocktail', 8);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Cranberry & Rum', 'Daiquiri', 8);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Sailors Yule', 'Nog', 8);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Cup O Jerry', 'Coffee', 8);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Sevilla', 'Spritz', 2);
INSERT INTO drinks (name, type, liquor_id) VALUES ('The Number 10', 'Martini', 2);
INSERT INTO drinks (name, type, liquor_id) VALUES ('London Dry', 'Negroni', 2);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Neat', 'Whisky', 3);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Summer Nights', 'Cocktail', 4);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Blackberry Smash', 'Sipper', 4);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Dirty Shirley', 'Old-school', 4);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Pineapple Rum', 'Cocktail', 5);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Island Rum', 'Punch', 5);
INSERT INTO drinks (name, type, liquor_id) VALUES ('Captains Passion', 'Punch', 5); 